org: drochag1
app: worldtime
service: api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    GOOGLE_MAPS_API_KEY: ${param:GOOGLE_MAPS_API_KEY}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  getPlaces:
    handler: handler.getPlaces
    events:
      - http:
          path: /get-places
          method: post
  getExtendedSuggestion:
    handler: handler.getExtendedSuggestion
    events:
      - http:
          path: /get-extended-suggestion
          method: post
